version: '3.2'

services:
  ibkr:
    image: finx-ibkr-tws-docker:latest
    env_file:
      - env-file-${IBKR_TRADING_MODE:-paper}
    ports:
      - "127.0.0.1:6080:6080"
      - "127.0.0.1:8888:8888"
    restart: unless-stopped
    stop_signal: SIGKILL
    environment:
      TWS_MAJOR_VRSN: 1012
